binary_sensor:
  - platform: template
    sensors:
      rain_next_3_days:
        friendly_name: "3 Day Forecast"
        device_class: moisture
        value_template: "{{ states('input_text.weather_forecast_json') }}"
        attribute_templates:
          forecast_checked: "{{ now().isoformat() }}"